#spring.application.name=api

  spring:
    application:
      name: api
    data:
      mongodb:
        uri: ${MONGODB_URI}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:7d}

  cloudinary:
    url: ${CLOUDINARY_CLOUD_URL}


